### ISSUE TITLE
Chat is unreliable

### ISSUE THREAD

**Issue by jwaa** [matrx-software/matrx#222] opened 2020-09-07 08:56 UTC
**Describe the bug**
There a few bugs/issues with the chat in MATRX (as found out during a [DASH sprint](https://ci.tno.nl/gitlab/dash/main/-/blob/dev-jeanine/dash_world/agents.py#L42))
The following were identified:
-	Chats exists, but every agent can see all the chats. This is not something we want in DASH, for instance we have a John Doe human agent who chats with systems but these should not be overheard by another human agent; the UAV Manager.
-	All agents can send to every chat, even if it is a chat between two other agents. So let's say our UAV Manager chats with a UAV called Spotter_1, then John Doe can also barge in that chat and start talking. However, the UAV Manager just see the messages pop-up without being able to see who send them (as in global chat).
-	At irregular times new messages only arrive when you refresh the page.

**To Reproduce**
See the [DASH repository, branch dev-jeanine](https://ci.tno.nl/gitlab/dash/main/-/blob/dev-jeanine/dash_world/agents.py#L42).

**Expected behavior**
The idea in DASH was that an agent, John Doe, sends a message to all (human/wizard) agents that need to talk to John Doe. Those agents should now have a chat open to them where they can start sending messages to John Doe. This is already a workaround of not being able to create a new chat with a certain agent. 

Given this chat, messages should be send without other (human) agents being able to read them, or even worse; chat back anonymously! Furthermore, messages should just pop-up consistently without requiring an actual refresh.

**Screenshots**
N/A

**Stacktrace**
N/A

**Additional context**
[@Jeanine](https://ci.tno.nl/gitlab/jeanine.vanbruggen-tno) worked with this from the DASH project, so contact her if you want more information.

**Comment by thaije** [comment] 2020-09-07 19:38
@jwaa In response to your points: 

> Chats exists, but every agent can see all the chats. This is not something we want in DASH, for instance we have a John Doe human agent who chats with systems but these should not be overheard by another human agent; the UAV Manager. 

I can't replicate this one. I cloned and ran the DASH dev-jeanine. I can see the John Doe human agent who receives a message from all other agents. The chat from the John Doe human agent:
![image](https://user-images.githubusercontent.com/2978372/92413378-1f1ea080-f150-11ea-94b2-2bc0fe1af81f.png)
However, there is no other Human Agent called UAV manager nor any other. If I add another John Doe or default Human Agent, they can't see any of the messages addressed to John Doe, or open any of John Doe's chats, see below. So how did you encounter this? 
![image](https://user-images.githubusercontent.com/2978372/92413526-d4515880-f150-11ea-852a-7b40d25ad3c6.png)

> All agents can send to every chat, even if it is a chat between two other agents. So let's say our UAV Manager chats with a UAV called Spotter_1, then John Doe can also barge in that chat and start talking. However, the UAV Manager just see the messages pop-up without being able to see who send them (as in global chat).

Same as above, how do you do this? 

> At irregular times new messages only arrive when you refresh the page.
Working on it. 


Another issue that has to be addressed is being able to start a chat with another agent. When you press the "+" icon, should you be able to see all other agents, and open a chat with them? Because for some experiments, it might not be desired to see a list of all (human)agents. That's why as it is implemented now it only works for teams (atleast I think that was the reason for the choice).

**Comment by jwaa** [comment] 2020-09-08 09:29
Good points, I just typed what Jeanine mailed me. So I would suggest you contact her for the first 2 points.

Can you elaborate a bit on the teams part and chat? I also thought we had something with teams and chat, but had no clue what this was. If I understand correctly you believe that agents that are in the same team, can start a chat with eachother using the "+" icon? That would prevent DASH from doing some creative loops to make chat work for them.

**Comment by Jeaninevbr** [comment] 2020-09-09 15:43
There is indeed no UAV manager yet. The problems described occur between HumanAgents and ''normal'' agents. So for example in DASH if John (HumanAgent) sends a message to Peter (nonhuman), this message also shows in the chat of Bobby and Colin. See also this screenshot: 

<img width="1923" alt="DASH_chat_issue (1)" src="https://user-images.githubusercontent.com/71027069/92619022-4a74cd00-f2c1-11ea-8706-7682ca1d5b72.png">

That other agents can interfere in chats that are not their own is not totally true, see next screenshot. Peter can send messages in the John/Colin chat, but they do not appear in the John and Colin dashboards.  So that is good news I guess. In the ideal version Peter would not even see this chat off course. 

<img width="1810" alt="DASH_chat_issue2" src="https://user-images.githubusercontent.com/71027069/92620204-adb32f00-f2c2-11ea-8b5d-27f4488e0383.png">

It is indeed interesting to test if this also occurs in the chats from HumanAgent to HumanAgent. I'll implement the UAV manager soon. 

Hope this clarifies! If not, feel free to contact :)

**Comment by thaije** [comment] 2020-09-09 16:08
@Jeaninevbr Thanks for the clarification. :) I'm going to look into it. In the mean time, did you check if it is not caused by cache issues? I.e. did you to ctrl + F5 when opening the web pages?

**Comment by thaije** [comment] 2020-09-18 11:06
@Jeaninevbr I was able to replicate the problem. It isn't caused by cache. I'm working on a update to the chat functionality of MATRX which will fix this issue as well most likely. After the update we can test if it is solved for this bug in DASH as well.

**Comment by jwaa** [comment] 2020-09-20 20:08
@thaije How is it coming along?

**Comment by thaije** [comment] 2020-09-21 20:08
https://github.com/matrx-software/matrx/tree/%23222_chat_unreliable. 
Fixed in v2.0.0 of MATRX

**Closed by thaije** 2020-09-21 20:08 UTC
Labels: bug
