### ISSUE TITLE
Passing a object_id to the DropAction always fails the action

### ISSUE THREAD

**Issue by thaije** [matrx-software/matrx#211] opened 2020-07-23 14:12 UTC
**Describe the bug**
If you pass the action argument "object_id" to the DropObject action, it always fails. 

**To Reproduce**
Pass a object_id of an object being carried by the current agent to the DropAction. 

**Expected behavior**
That passing a object_id to the DropAction drops that specific object.

It can be seen here that there actually is code in place to process a object_id being passed to the DropAction: 
https://github.com/matrx-software/matrx/blob/master/matrx/actions/object_actions.py#L880

However, this doesn't work, as it looks in the `agent.is_carrying` list for the object_id. But this list contains complete objects, and not object_ids. 

**Stacktrace**
There is no error, it just returns False for the `is_possible` of the DropAction.

**Comment by jwaa** [comment] 2021-01-12 16:09
Duplicate of #236, is now fixed in #237

**Closed by jwaa** 2021-01-12 16:09 UTC
Labels: bug
