### ISSUE TITLE
Messages not updated

### ISSUE THREAD

**Issue by jwaa** [matrx-software/matrx#120] opened 2020-03-25 09:51 UTC
**Describe the bug**
When sending messages between two human agents, the message box is not updated until I manually refresh.

**To Reproduce**
1. Run `main.py` with the `test_vis.py` case.
2. Open the god view and the two human agent views
3. Run the world through the god view
4. Open the chat windows in both human agents
5. Start sending messages from one agent to another.
6. See the messages not arriving
7. Refresh; voila! There are the messages.

**Expected behavior**
I expect the messages to arrive instantly.

**Screenshots**
N/A

**Stacktrace**
N/A

**Additional context**
I am using Firefox v72.0.2

**Comment by thaije** [comment] 2020-04-10 18:11
There are a couple of things that could be the cause. 

Option 1:
- Cache. Completely clear all cache and cookies of your browser, or test it incognito. This might be the cause, which was it the first time for me.

Option 2:
- Test it with the two screens open side-by-side. They have to be in view, otherwise Firefox/chrome will throttle the processing of that tab, skipping frames, and thus chat messages. If you do it like this, do you still have the issue? 

Option 3: 
- You tried both of the above and it is still not working. Then it is a new bug. 

Neverthless, the chat robustness can be improved, such that it also always works even if the browser is hidden. 

The difficulty with syncing of messages is that the browser sometimes throttles the front-end, which leads to frame drops and skipping of ticks. This wouldn't be a problem if you sync all messages every tick, but as that is not efficient you would like to sync only the messages that are missing in the frontend. However, how do you know which messages are missing? 

Right now, the state and messages are requested for the same tick by the frontend. The latest tick. 
An option is to split this. The state is requested of the latest tick, and the messages of the last known tick. I'll brainstorm some more on this and see if I can implement it.

**Comment by jwaa** [comment] 2020-04-15 07:22
See #155 for a potential solution, partial solution at best though as it does not solve the prospect issue.

**Comment by thaije** [comment] 2020-04-15 10:15
For this specific bug the issue lies more with the missing of frames in the frontend (e.g. due to throttling of background tabs), which leads to missed messages. As such, for this specific issue I think #155 wouldn't influence or change the bug.

**Comment by jwaa** [comment] 2020-04-15 10:54
I think I commented this in the wrong issue...

**Comment by thaije** [comment] 2021-01-14 14:07
Fixed in MATRX 2.0

**Closed by thaije** 2021-01-14 14:07 UTC
Labels: bug, front-end
